import type { Lang } from "./i18n";

/**
 * The system specification's words (Settings › About), English first and
 * Serbian with the same keys (a missing one does not compile). They live
 * beside it rather than in i18n.ts, which has only its title and the words
 * Settings' search finds it by. Group names are shown in capitals.
 */
const en = {
  intro: "Zaklon's versions and this computer's details, to send with a bug report. Nothing secret is in it: no passwords, no keys.",
  copyAll: "Copy all",
  copied: "Copied. Paste it into the bug report.",
  copyFailed: "Could not copy. Select the table and copy it instead.",
  loading: "Asking the hub…",
  reading: "reading…",
  na: "n/a",
  none: "none",
  hubUnreachable: "The hub could not be reached, so its part is missing.",
  title: "Zaklon system specification",

  gApp: "Application",
  gHub: "Hub",
  gBuiltWith: "Built with",
  gDatabase: "Database",
  gAssistant: "AI assistant",
  gLibrary: "Library",
  gMaps: "Maps",
  gNetwork: "Network",

  version: "Zaklon version",
  phoneApp: "Phone app version",
  build: "Build",
  commit: "commit",
  mode: "Mode",
  release: "release",
  development: "development",
  windows: "Windows version",
  system: "System",
  buildNo: "build",
  webview2: "WebView2",
  android: "Android version",
  webview: "WebView (Chrome)",

  connectedHub: "Connected hub",
  notConnected: "not connected",
  lastReached: "Last reached",
  justNow: "just now",
  hubVersion: "Hub version",
  hubComputer: "Hub computer",

  hubServer: "Hub (server)",
  interface: "Interface",
  apps: "Desktop and phone app",
  database: "Database",
  aiEngine: "AI engine",
  libraryEngine: "Library engine",
  zaklonMap: "Zaklon map",
  navigation: "Navigation (phones)",
  separateApp: "a separate app",
  notInstalled: "not installed",

  dbSystem: "System",
  size: "Size",
  schema: "Schema",
  schemaAtStart: "no version number; made on every start",
  migrations: "migrations",
  lastBackup: "Last backup",
  noBackup: "none yet",

  engine: "Engine",
  engineMissing: "not installed",
  engineNoModel: "no model yet",
  engineStopped: "ready, starts on the first question",
  engineStarting: "starting",
  engineReady: "running",
  engineFailed: "did not start",
  models: "Installed models",
  inUse: "In use",
  memory: "Memory (RAM)",
  recommends: "recommends",
  noModelFits: "no model fits",
  processor: "Processor",

  packs: "Packs installed",
  folder: "Library folder",
  drive: "Drive",
  free: "free of",

  worldMap: "Zaklon world map",
  overviewOnly: "overview only",
  noMap: "none",
  overview: "World overview",
  included: "included",
  notIncluded: "not included",
  comapsApp: "CoMaps app",
  onHub: "on the hub",
  notOnHub: "not on the hub yet",
  comapsMaps: "CoMaps maps",

  addresses: "Hub addresses",
  port: "Port",
  profile: "Network profile",
  phones: "Phones paired",
  fingerprint: "Certificate",
  netPrivate: "Private",
  netPublic: "Public",
  netDomain: "Domain",
};

export type SpecText = typeof en;

const sr: SpecText = {
  intro: "Verzije Zaklona i podaci o ovom računaru, za prijavu greške. Ovde nema ničeg tajnog: ni lozinki ni ključeva.",
  copyAll: "Kopiraj sve",
  copied: "Kopirano. Nalepi to u prijavu greške.",
  copyFailed: "Kopiranje nije uspelo. Označi tabelu i kopiraj je ručno.",
  loading: "Pitam hub…",
  reading: "čitam…",
  na: "nije poznato",
  none: "nema",
  hubUnreachable: "Hub nije dostupan, pa njegov deo nedostaje.",
  title: "Specifikacija sistema Zaklon",

  gApp: "Aplikacija",
  gHub: "Hub",
  gBuiltWith: "Napravljeno sa",
  gDatabase: "Baza podataka",
  gAssistant: "AI asistent",
  gLibrary: "Biblioteka",
  gMaps: "Mape",
  gNetwork: "Mreža",

  version: "Verzija Zaklona",
  phoneApp: "Verzija aplikacije na telefonu",
  build: "Build",
  commit: "komit",
  mode: "Režim",
  release: "izdanje",
  development: "razvojna verzija",
  windows: "Verzija Windowsa",
  system: "Sistem",
  buildNo: "build",
  webview2: "WebView2",
  android: "Verzija Androida",
  webview: "WebView (Chrome)",

  connectedHub: "Povezan hub",
  notConnected: "nije povezan",
  lastReached: "Poslednji kontakt",
  justNow: "upravo sada",
  hubVersion: "Verzija huba",
  hubComputer: "Računar huba",

  hubServer: "Hub (server)",
  interface: "Interfejs",
  apps: "Aplikacija za računar i telefon",
  database: "Baza podataka",
  aiEngine: "AI motor",
  libraryEngine: "Motor biblioteke",
  zaklonMap: "Zaklon mapa",
  navigation: "Navigacija (telefoni)",
  separateApp: "posebna aplikacija",
  notInstalled: "nije instaliran",

  dbSystem: "Sistem",
  size: "Veličina",
  schema: "Šema",
  schemaAtStart: "bez broja verzije; pravi se pri svakom pokretanju",
  migrations: "migracije",
  lastBackup: "Poslednja rezervna kopija",
  noBackup: "još nema",

  engine: "Motor",
  engineMissing: "nije instaliran",
  engineNoModel: "još nema modela",
  engineStopped: "spreman, pokreće se na prvo pitanje",
  engineStarting: "pokreće se",
  engineReady: "radi",
  engineFailed: "nije se pokrenuo",
  models: "Instalirani modeli",
  inUse: "U upotrebi",
  memory: "Memorija (RAM)",
  recommends: "preporučuje",
  noModelFits: "nijedan model ne staje",
  processor: "Procesor",

  packs: "Instalirani paketi",
  folder: "Folder biblioteke",
  drive: "Disk",
  free: "slobodno od",

  worldMap: "Zaklon mapa sveta",
  overviewOnly: "samo pregled sveta",
  noMap: "nema",
  overview: "Pregled sveta",
  included: "uključen",
  notIncluded: "nije uključen",
  comapsApp: "Aplikacija CoMaps",
  onHub: "na hubu",
  notOnHub: "još nije na hubu",
  comapsMaps: "CoMaps mape",

  addresses: "Adrese huba",
  port: "Port",
  profile: "Mrežni profil",
  phones: "Upareni telefoni",
  fingerprint: "Sertifikat",
  netPrivate: "Privatna",
  netPublic: "Javna",
  netDomain: "Domen",
};

export const SPEC_TEXT: Record<Lang, SpecText> = { en, sr };
