import type { Lang } from "./i18n";
import type { CropId } from "./water";

/**
 * The water calculator's words, English first and Serbian with the same keys
 * (a missing one does not compile). They live beside the tool rather than in
 * i18n.ts, which has the tool's name and description. "{n}" and the like are
 * filled in by `fill`.
 */
const en = {
  intro: "How much water to keep at home for an emergency, and how much a vegetable garden needs with drip irrigation.",
  parts: "Part of the calculator",
  partDrink: "Drinking water to store",
  partDrip: "Drip irrigation for a garden",
  loading: "Loading…",
  saving: "Saving…",
  saved: "Saved on the hub: the same numbers for the whole household.",
  changedBy: "Last change: {who}, {when}.",
  theLaptop: "the laptop",
  notSaved: "Not saved:",
  fromLink: "Opened from a link. These numbers are not saved, and the household's are unchanged.",
  unsaved: "The hub could not be reached, so these numbers are not saved.",
  keep: "Save for the household",
  showSaved: "Show the saved numbers",
  less: "Less",
  more: "More",
  howTitle: "How this is calculated",
  sources: "Sources",

  // Drinking water
  whoTitle: "Who needs water",
  adults: "Adults",
  children: "Children",
  smallPets: "Cats and small dogs",
  largePets: "Large dogs",
  daysTitle: "For how many days",
  days3: "3 days",
  days7: "1 week",
  days14: "2 weeks",
  daysOther: "Other",
  daysNumber: "Number of days",
  needMore: "Children, nursing mothers and sick people may need more water, and in very hot weather the need can double.",
  storeTitle: "Water to store",
  drinkingLabel: "for drinking and cooking",
  drinkingHow: "At least one gallon (3.8 L) per person a day, as Ready.gov advises, for {days}.",
  hygieneLabel: "with washing and basic hygiene",
  hygieneHow: "At least 15 L per person a day, the minimum of the humanitarian Sphere standards.",
  containersTitle: "How many containers that is",
  drum: "200 L drum",
  rowDrinking: "Drinking and cooking",
  rowHygiene: "With hygiene",
  keepFresh: "Keep it in clean containers made for food or drinks, somewhere cool and dark. Replace water you filled yourself every six months.",
  safeTitle: "Make water safe to drink",
  boilTitle: "Boil it",
  boilText: "Bring clear water to a rolling boil for 1 minute, or for 3 minutes above 1,000 m. Let it cool. Boiling is the best method.",
  bleachTitle: "Or add bleach",
  bleachText: "Use plain, unscented household bleach with 5–9% sodium hypochlorite; if its label says how to disinfect drinking water, follow that. Add 2 drops per liter of clear water, 4 if it is cloudy. For a 20 L canister: 40 drops, about 2.5 mL (half a teaspoon). Stir and wait at least 30 minutes.",
  cloudyText: "Let cloudy water settle, then filter it through a clean cloth, paper towel or coffee filter before you boil it or add bleach.",
  chemicalsWarn: "Water with fuel, chemicals or poison in it cannot be made safe by boiling, bleach or filtering.",
  safeSource: "Source: CDC and EPA; not endorsed by them.",
  drinkSources: "Amounts: Ready.gov and the Sphere Handbook.",
  howDrink: [
    "Drinking and cooking = (adults + children) × 3.8 L × days, plus the pets. 3.8 L is Ready.gov's one gallon per person a day.",
    "With hygiene = (adults + children) × 15 L × days, plus the pets. 15 L per person a day is the Sphere minimum for drinking, cooking and basic hygiene.",
    "Pets: about 65 mL per kg of body weight a day, a common veterinary rule of thumb (Ready.gov gives no amount). A cat or a small dog is counted as 10 kg (0.65 L a day), a large dog as 30 kg (1.95 L a day).",
    "Containers: the liters divided by the size of one container, rounded up.",
  ],

  // Drip irrigation
  bedsTitle: "Your beds",
  bedsIntro: "Measure each bed and choose what grows in it.",
  bedName: "Bed {n}",
  sizeBy: "Size given as",
  bySize: "Length × width",
  byArea: "Area",
  length: "Length (m)",
  width: "Width (m)",
  area: "Area (m²)",
  crop: "What grows there",
  rows: "Drip lines along the bed",
  rowsHint: "Suggested for this width: {n}",
  addBed: "Add a bed",
  removeBed: "Remove",
  weatherTitle: "Weather in that month",
  weatherIntro: "Plan for the hottest month: the garden needs the most water then.",
  month: "Month",
  lat: "Latitude (°)",
  latHint: "North is positive, south negative.",
  city: "Or a city nearby",
  cityPick: "Pick a city",
  tmax: "Usual daytime high (°C)",
  tmin: "Usual night low (°C)",
  tempHint: "Typical for that month where you live; a climate table or a weather forecast has them.",
  rain: "Rain in that month (mm)",
  rainHint: "Optional. Rain that falls on the beds is taken off what they need.",
  tempsWrong: "The night low must not be above the daytime high.",
  et0Is: "In this weather a lawn loses about {n} mm of water a day.",
  et0Name: "This is the reference evapotranspiration, ET₀.",
  et0Missing: "Enter the latitude and both temperatures to work out ET₀, or enter your own below.",
  et0Own: "Your own ET₀ (mm a day)",
  et0OwnHint: "Optional: if a local weather service gives it, it is used instead.",
  et0Used: "Your own ET₀ is used: {n} mm a day.",
  dripTitle: "Drip line",
  spacing: "Dripper spacing",
  flow: "Dripper flow",
  resultTitle: "What the garden needs",
  perDay: "Water a day",
  perWeek: "Water a week",
  drippers: "Drippers",
  totalFlow: "Flow of all drippers",
  runTime: "Run the water",
  runOnce: "{n} min a day",
  runTwice: "{n} min twice a day (morning and evening)",
  tank: "Tank for one day",
  tankBucket: "a 20 L bucket",
  tankDrum: "a 200 L drum",
  tankTank: "a 1,000 L tank",
  tankTanks: "{n} tanks of 1,000 L",
  pressureNote: "A bucket or drum raised about 1 m is enough to run drip lines by gravity. But 1 m of height gives only about 0.1 bar, much less than drippers are rated for, so they drip slower than it says on them. Hold a cup under one dripper for 10 minutes: at its rating a {flow} L/h dripper gives about {ml} mL. If it gives less, run the water longer.",
  byBed: "Bed by bed",
  bedLine: "{area} m² · {liters} L a day · {drippers}",
  dripperWord: ["dripper", "drippers", "drippers"] as [string, string, string],
  needBeds: "Enter the size of at least one bed.",
  roofTitle: "Rainwater from your roof",
  roofArea: "Roof area (m²)",
  roofHint: "The ground the roof covers, measured from above, not along the slope.",
  roofResult: "In a month with {rain} mm of rain, the roof collects about {liters} L.",
  roofDays: "That is enough for this garden for about {days}.",
  roofNeedRain: "Enter the month's rain above to see how much the roof collects.",
  roofWarn: "Rainwater must be treated before drinking: boil it or add bleach, as in Drinking water to store.",
  kcTitle: "Crop coefficients (Kc)",
  howDrip: [
    "ET₀ = 0.0023 × Ra × (Tmean + 17.8) × √(Tmax − Tmin), the Hargreaves–Samani (1985) method; Tmean is the average of the high and the low.",
    "Ra is the sun's radiation at the top of the atmosphere for the latitude and the middle of the month, counted as the millimeters of water it can evaporate (FAO-56 formulas).",
    "Water a day for a bed = (ET₀ × Kc − rain a day) ÷ 0.9 × area. Kc says how much a crop uses compared with a lawn; 0.9 because drip gets about 90% of the water to the roots. 1 mm on 1 m² is 1 L.",
    "Drippers in a bed = drip lines × (length ÷ spacing); a bed given only by its area gets lines 40 cm apart.",
    "Minutes a day = liters a day ÷ (drippers × flow) × 60; more than 60 minutes is split into two runs.",
    "Roof: area × rain (mm) × 0.8 = liters; 0.8 allows for what splashes off, evaporates or is let run off first.",
  ],
  dripSources:
    "Crop coefficients: USDA NRCS, National Engineering Handbook Part 623, Chapter 2 (1993). ET₀: Hargreaves and Samani (1985). Gravity drip kits: Palada M. et al. 2011. More Crop Per Drop. AVRDC – The World Vegetable Center (CC BY-SA 3.0).",
  dayWord: ["day", "days", "days"] as [string, string, string],
  crops: {
    greens: "Leafy greens (lettuce, spinach, cabbage)",
    tomatoes: "Tomatoes, peppers, eggplant",
    squash: "Cucumbers, squash, melons",
    beans: "Beans and peas",
    roots: "Root crops (carrots, beets)",
    potatoes: "Potatoes",
    onions: "Onions and garlic",
    corn: "Sweet corn",
    strawberries: "Strawberries",
    bushes: "Fruit bushes (raspberries, currants)",
  } satisfies Record<CropId, string>,
  months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
};

const sr: typeof en = {
  intro: "Koliko vode da čuvaš kod kuće za slučaj nužde, i koliko vode treba povrtnjaku koji se zaliva kap po kap.",
  parts: "Deo kalkulatora",
  partDrink: "Voda za piće u rezervi",
  partDrip: "Navodnjavanje kap po kap",
  loading: "Učitavam…",
  saving: "Čuvam…",
  saved: "Sačuvano na hubu: isti brojevi za celo domaćinstvo.",
  changedBy: "Poslednja izmena: {who}, {when}.",
  theLaptop: "laptop",
  notSaved: "Nije sačuvano:",
  fromLink: "Otvoreno preko linka. Ovi brojevi nisu sačuvani, a brojevi domaćinstva su nepromenjeni.",
  unsaved: "Hub nije dostupan, pa ovi brojevi nisu sačuvani.",
  keep: "Sačuvaj za domaćinstvo",
  showSaved: "Prikaži sačuvane brojeve",
  less: "Manje",
  more: "Više",
  howTitle: "Kako se ovo računa",
  sources: "Izvori",

  whoTitle: "Kome treba voda",
  adults: "Odrasli",
  children: "Deca",
  smallPets: "Mačke i mali psi",
  largePets: "Veliki psi",
  daysTitle: "Za koliko dana",
  days3: "3 dana",
  days7: "1 nedelja",
  days14: "2 nedelje",
  daysOther: "Drugo",
  daysNumber: "Broj dana",
  needMore: "Deci, dojiljama i bolesnima može trebati više vode, a po velikoj vrućini potreba može da se udvostruči.",
  storeTitle: "Koliko vode da čuvaš",
  drinkingLabel: "za piće i kuvanje",
  drinkingHow: "Najmanje 3,8 L (jedan galon) po osobi dnevno, kako savetuje Ready.gov, za {days}.",
  hygieneLabel: "uz pranje i osnovnu higijenu",
  hygieneHow: "Najmanje 15 L po osobi dnevno, minimum iz humanitarnih standarda Sphere.",
  containersTitle: "Koliko je to posuda",
  drum: "Bure od 200 L",
  rowDrinking: "Piće i kuvanje",
  rowHygiene: "Uz higijenu",
  keepFresh: "Čuvaj je u čistim posudama za hranu ili piće, na hladnom i tamnom mestu. Vodu koju si sam natočio menjaj na svakih šest meseci.",
  safeTitle: "Kako da voda bude bezbedna za piće",
  boilTitle: "Prokuvaj je",
  boilText: "Neka bistra voda snažno ključa 1 minut, a iznad 1.000 m nadmorske visine 3 minuta. Ostavi je da se ohladi. Kuvanje je najbolji način.",
  bleachTitle: "Ili dodaj varikinu",
  bleachText: "Koristi običnu varikinu bez mirisa, sa 5–9% natrijum-hipohlorita; ako na etiketi piše kako se njome dezinfikuje voda za piće, uradi tako. Dodaj 2 kapi na litar bistre vode, a 4 ako je mutna. Za kanister od 20 L: 40 kapi, oko 2,5 mL (pola kafene kašičice). Promešaj i sačekaj najmanje 30 minuta.",
  cloudyText: "Mutnu vodu prvo ostavi da se slegne, pa je procedi kroz čistu krpu, papirni ubrus ili filter za kafu, i tek onda je prokuvaj ili dodaj varikinu.",
  chemicalsWarn: "Voda u kojoj ima goriva, hemikalija ili otrova ne može se učiniti bezbednom ni kuvanjem, ni varikinom, ni ceđenjem.",
  safeSource: "Izvor: CDC i EPA; oni ne stoje iza ovog alata.",
  drinkSources: "Količine: Ready.gov i priručnik Sphere.",
  howDrink: [
    "Piće i kuvanje = (odrasli + deca) × 3,8 L × broj dana, plus ljubimci. 3,8 L je jedan galon po osobi dnevno, koliko savetuje Ready.gov.",
    "Uz higijenu = (odrasli + deca) × 15 L × broj dana, plus ljubimci. 15 L po osobi dnevno je minimum standarda Sphere za piće, kuvanje i osnovnu higijenu.",
    "Ljubimci: oko 65 mL po kilogramu telesne mase dnevno, uobičajeno veterinarsko pravilo (Ready.gov ne daje količinu). Mačka ili mali pas računa se kao 10 kg (0,65 L dnevno), veliki pas kao 30 kg (1,95 L dnevno).",
    "Posude: litri podeljeni zapreminom jedne posude, zaokruženo naviše.",
  ],

  bedsTitle: "Tvoje leje",
  bedsIntro: "Izmeri svaku leju i izaberi šta raste u njoj.",
  bedName: "Leja {n}",
  sizeBy: "Veličina zadata kao",
  bySize: "Dužina × širina",
  byArea: "Površina",
  length: "Dužina (m)",
  width: "Širina (m)",
  area: "Površina (m²)",
  crop: "Šta raste",
  rows: "Broj creva duž leje",
  rowsHint: "Predlog za ovu širinu: {n}",
  addBed: "Dodaj leju",
  removeBed: "Ukloni",
  weatherTitle: "Vreme u tom mesecu",
  weatherIntro: "Planiraj za najtopliji mesec: tada bašti treba najviše vode.",
  month: "Mesec",
  lat: "Geografska širina (°)",
  latHint: "Sever je pozitivan, jug negativan.",
  city: "Ili grad u blizini",
  cityPick: "Izaberi grad",
  tmax: "Uobičajena dnevna najviša (°C)",
  tmin: "Uobičajena noćna najniža (°C)",
  tempHint: "Uobičajene za taj mesec u tvom kraju; ima ih u klimatskim tabelama ili u vremenskoj prognozi.",
  rain: "Kiša u tom mesecu (mm)",
  rainHint: "Nije obavezno. Kiša koja padne na leje oduzima se od onoga što im treba.",
  tempsWrong: "Noćna najniža ne sme da bude viša od dnevne najviše.",
  et0Is: "Po ovakvom vremenu travnjak gubi oko {n} mm vode dnevno.",
  et0Name: "To je referentna evapotranspiracija, ET₀.",
  et0Missing: "Unesi geografsku širinu i obe temperature da se izračuna ET₀, ili ispod unesi svoju.",
  et0Own: "Tvoja ET₀ (mm dnevno)",
  et0OwnHint: "Nije obavezno: ako je daje lokalna meteorološka služba, koristi se ona.",
  et0Used: "Koristi se tvoja ET₀: {n} mm dnevno.",
  dripTitle: "Creva za kapanje",
  spacing: "Razmak kapaljki",
  flow: "Protok kapaljke",
  resultTitle: "Šta bašti treba",
  perDay: "Vode dnevno",
  perWeek: "Vode nedeljno",
  drippers: "Broj kapaljki",
  totalFlow: "Protok svih kapaljki",
  runTime: "Puštaj vodu",
  runOnce: "{n} min dnevno",
  runTwice: "{n} min dvaput dnevno (ujutru i uveče)",
  tank: "Posuda za jedan dan",
  tankBucket: "kofa od 20 L",
  tankDrum: "bure od 200 L",
  tankTank: "rezervoar od 1.000 L",
  tankTanks: "{n} rezervoara od 1.000 L",
  pressureNote: "Kofa ili bure podignuti oko 1 m dovoljni su da voda sama teče kroz creva. Ali 1 m visine daje samo oko 0,1 bar, mnogo manje nego što je predviđeno za kapaljke, pa one kaplju sporije nego što piše na njima. Drži čašu ispod jedne kapaljke 10 minuta: kapaljka od {flow} L/h trebalo bi da da oko {ml} mL. Ako da manje, puštaj vodu duže.",
  byBed: "Po lejama",
  bedLine: "{area} m² · {liters} L dnevno · {drippers}",
  dripperWord: ["kapaljka", "kapaljke", "kapaljki"],
  needBeds: "Unesi veličinu bar jedne leje.",
  roofTitle: "Kišnica sa krova",
  roofArea: "Površina krova (m²)",
  roofHint: "Površina koju krov pokriva, merena odozgo, a ne niz kosinu.",
  roofResult: "U mesecu sa {rain} mm kiše krov skupi oko {liters} L.",
  roofDays: "To je dovoljno za ovu baštu za oko {days}.",
  roofNeedRain: "Unesi kišu u tom mesecu (iznad) da vidiš koliko krov skupi.",
  roofWarn: "Kišnicu pre pijenja obavezno prokuvaj ili dodaj varikinu, kao u delu Voda za piće u rezervi.",
  kcTitle: "Koeficijenti biljaka (Kc)",
  howDrip: [
    "ET₀ = 0,0023 × Ra × (Tsr + 17,8) × √(Tmax − Tmin), metoda Hargreaves–Samani (1985); Tsr je prosek najviše i najniže temperature.",
    "Ra je sunčevo zračenje na vrhu atmosfere za tu geografsku širinu i sredinu meseca, izraženo kao milimetri vode koje može da ispari (formule iz FAO-56).",
    "Voda dnevno za leju = (ET₀ × Kc − kiša dnevno) ÷ 0,9 × površina. Kc kaže koliko biljka troši u poređenju sa travnjakom; 0,9 jer kap po kap oko 90% vode dovede do korena. 1 mm na 1 m² je 1 L.",
    "Kapaljke u leji = broj creva × (dužina ÷ razmak); za leju zadatu samo površinom creva se računaju na 40 cm jedno od drugog.",
    "Minuta dnevno = litara dnevno ÷ (kapaljke × protok) × 60; preko 60 minuta deli se na dva puštanja.",
    "Krov: površina × kiša (mm) × 0,8 = litara; 0,8 jer deo vode prsne, ispari ili se pusti da prvo oteče.",
  ],
  dripSources:
    "Koeficijenti biljaka: USDA NRCS, National Engineering Handbook Part 623, Chapter 2 (1993). ET₀: Hargreaves i Samani (1985). Gravitacioni sistemi kap po kap: Palada M. et al. 2011. More Crop Per Drop. AVRDC – The World Vegetable Center (CC BY-SA 3.0).",
  dayWord: ["dan", "dana", "dana"],
  crops: {
    greens: "Lisnato povrće (salata, spanać, kupus)",
    tomatoes: "Paradajz, paprika, plavi patlidžan",
    squash: "Krastavci, tikve, dinje, lubenice",
    beans: "Pasulj, boranija, grašak",
    roots: "Korenasto povrće (šargarepa, cvekla)",
    potatoes: "Krompir",
    onions: "Crni i beli luk",
    corn: "Kukuruz šećerac",
    strawberries: "Jagode",
    bushes: "Bobičasto voće (malina, ribizla)",
  },
  months: ["Januar", "Februar", "Mart", "April", "Maj", "Jun", "Jul", "Avgust", "Septembar", "Oktobar", "Novembar", "Decembar"],
};

export type WaterText = typeof en;
export const WATER_TEXT: Record<Lang, WaterText> = { en, sr };

/** The word for `n` things: English [one, many, many], Serbian [1, 2-4, 5 and up] ("1 dan", "3 dana"). */
export function plural(lang: Lang, n: number, forms: readonly [string, string, string]): string {
  if (lang === "sr") {
    const last = n % 10;
    const lastTwo = n % 100;
    if (last === 1 && lastTwo !== 11) return forms[0];
    if (last >= 2 && last <= 4 && (lastTwo < 12 || lastTwo > 14)) return forms[1];
    return forms[2];
  }
  return n === 1 ? forms[0] : forms[1];
}

/** "{n} min" with n = 5 -> "5 min". */
export function fill(text: string, vars: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
}

/** Cities to take the latitude from (degrees, south negative), for people who do not know theirs. */
export const CITIES: { id: string; en: string; sr: string; lat: number }[] = [
  { id: "belgrade", en: "Belgrade", sr: "Beograd", lat: 44.8 },
  { id: "novi-sad", en: "Novi Sad", sr: "Novi Sad", lat: 45.3 },
  { id: "nis", en: "Niš", sr: "Niš", lat: 43.3 },
  { id: "kragujevac", en: "Kragujevac", sr: "Kragujevac", lat: 44.0 },
  { id: "subotica", en: "Subotica", sr: "Subotica", lat: 46.1 },
  { id: "podgorica", en: "Podgorica", sr: "Podgorica", lat: 42.4 },
  { id: "sarajevo", en: "Sarajevo", sr: "Sarajevo", lat: 43.9 },
  { id: "banja-luka", en: "Banja Luka", sr: "Banja Luka", lat: 44.8 },
  { id: "zagreb", en: "Zagreb", sr: "Zagreb", lat: 45.8 },
  { id: "ljubljana", en: "Ljubljana", sr: "Ljubljana", lat: 46.1 },
  { id: "skopje", en: "Skopje", sr: "Skoplje", lat: 42.0 },
  { id: "sofia", en: "Sofia", sr: "Sofija", lat: 42.7 },
  { id: "bucharest", en: "Bucharest", sr: "Bukurešt", lat: 44.4 },
  { id: "budapest", en: "Budapest", sr: "Budimpešta", lat: 47.5 },
  { id: "vienna", en: "Vienna", sr: "Beč", lat: 48.2 },
  { id: "berlin", en: "Berlin", sr: "Berlin", lat: 52.5 },
  { id: "london", en: "London", sr: "London", lat: 51.5 },
  { id: "paris", en: "Paris", sr: "Pariz", lat: 48.9 },
  { id: "madrid", en: "Madrid", sr: "Madrid", lat: 40.4 },
  { id: "rome", en: "Rome", sr: "Rim", lat: 41.9 },
  { id: "athens", en: "Athens", sr: "Atina", lat: 38.0 },
  { id: "stockholm", en: "Stockholm", sr: "Stokholm", lat: 59.3 },
  { id: "new-york", en: "New York", sr: "Njujork", lat: 40.7 },
  { id: "chicago", en: "Chicago", sr: "Čikago", lat: 41.9 },
  { id: "los-angeles", en: "Los Angeles", sr: "Los Anđeles", lat: 34.1 },
  { id: "toronto", en: "Toronto", sr: "Toronto", lat: 43.7 },
  { id: "sydney", en: "Sydney", sr: "Sidnej", lat: -33.9 },
];
